/**
 * Do not edit this file.
 * This is to show a env flag on staging only
 */

const url = window.location.href;
const stagingApp = 'dazzling-lollipop-428ab6';
if (url.includes(stagingApp)) {
  const env = document.createElement('div');
  env.id = 'env';
  env.style.backgroundColor = '#e67e22';
  env.style.position = 'fixed';
  env.style.top = '0';
  env.style.left = '0';
  env.style.width = '100%';
  env.style.zIndex = '9999';
  env.style.padding = '10px';
  env.style.color = '#fff';
  env.style.textTransform = 'uppercase';
  env.style.textAlign = 'center';
  env.textContent = 'Staging Environment';
  document.body.appendChild(env);

  document.body.style.paddingTop = env.offsetHeight + 'px';
}
